import pandas as pd
import numpy as np
import faiss
import os

class FaissCandidateGenerator:
    def __init__(self, top_k=15):
        print("=== Role 2: FAISS Algorithmic Blocking Engine ===")
        self.top_k = top_k  # How many candidates to generate per Source 1 entity
        self.dimension = 384  # Size of MiniLM-L12-v2 embeddings

    def build_and_search(self):
        # 1. Load the cleaned text data and embeddings generated by Role 1
        print("[*] Loading cleaned TSV data and GPU embeddings...")
        try:
            s1_df = pd.read_csv("data/clean_data/test_source1_clean.tsv", sep='\t')
            s2_df = pd.read_csv("data/clean_data/test_source2_clean.tsv", sep='\t')
            s3_df = pd.read_csv("data/clean_data/test_source3_clean.tsv", sep='\t')
            
            s1_embs = np.load("data/clean_data/test_source1_clean_embeddings.npy").astype('float32')
            s2_embs = np.load("data/clean_data/test_source2_clean_embeddings.npy").astype('float32')
            s3_embs = np.load("data/clean_data/test_source3_clean_embeddings.npy").astype('float32')
        except FileNotFoundError:
            print("❌ Error: Cleaned data or embeddings missing! Did Role 1 run the GPU script yet?")
            return

        # Combine S2 and S3 into a single 'Candidate Pool'
        candidate_pool_df = pd.concat([s2_df, s3_df], ignore_index=True)
        candidate_pool_embs = np.vstack([s2_embs, s3_embs])

        # 2. Build the FAISS Index (Extremely fast C++ similarity search)
        print(f"[*] Building FAISS Index with {len(candidate_pool_df)} candidates...")
        # L2 normalization for Cosine Similarity
        faiss.normalize_L2(candidate_pool_embs)
        
        # Using IndexFlatIP (Inner Product) since vectors are normalized (equals Cosine Similarity)
        index = faiss.IndexFlatIP(self.dimension)
        index.add(candidate_pool_embs)
        print("[*] FAISS Index built successfully!")

        # 3. Perform the Massive Search
        print(f"[*] Querying FAISS index for {len(s1_df)} Source 1 entities...")
        faiss.normalize_L2(s1_embs)
        
        # D contains similarities (0.0 to 1.0), I contains the index/row number of the match
        D, I = index.search(s1_embs, self.top_k)

        # 4. Generate candidate_pairs.tsv format
        print("[*] Formatting results for Role 3...")
        candidate_pairs = []
        
        for i in range(len(s1_df)):
            s1_id = s1_df.iloc[i]['entity_id']
            
            # Get the actual entity_ids of the candidates using the FAISS indices
            # We filter out matches that have a terrible cosine similarity (e.g. < 0.6) to keep precision high
            good_candidates = []
            for rank, candidate_idx in enumerate(I[i]):
                similarity_score = D[i][rank]
                if similarity_score > 0.60: # Threshold to drop absolute garbage matches early
                    good_candidates.append(candidate_pool_df.iloc[candidate_idx]['entity_id'])
            
            # Join with commas as requested by Hackathon rules
            cand_string = ",".join(good_candidates)
            candidate_pairs.append({'source1_entity_id': s1_id, 'candidate_entity_ids': cand_string})

        # Save the final file
        os.makedirs("output", exist_ok=True)
        out_df = pd.DataFrame(candidate_pairs)
        out_df.to_csv("output/candidate_pairs.tsv", sep='\t', index=False)
        print(f"✅ Saved massive candidate generation to: output/candidate_pairs.tsv")
        print("🎉 Role 2 Complete! Handing off to Role 3 (Tanuj) for LightGBM Scoring.")

if __name__ == "__main__":
    blocker = FaissCandidateGenerator(top_k=15)
    blocker.build_and_search()
