"""
ML Challenge 2026: Business Entity Resolution Pipeline Configuration
Role: The Judge (Role 3: ML & Feature Engineering)

Design Rationale & Architectural Notes:
----------------------------------------
1. Modularity & Swappability:
   - Config provides a single source of truth for all filesystem paths, model parameters,
     and feature engineering hyperparameters.
   - Switching between the synthetic testbed (`fake_data/`) and the real competition data
     (`student_resource/dataset/`) is governed by a single boolean flag (`USE_FAKE_DATA`).

2. Model Architecture & Open Source Constraints:
   - Challenge constraint: Final model must be <8 Billion parameters and licensed under MIT/Apache 2.0.
   - Feature classifier: LightGBM GBDT (fast, handles mixed categorical/continuous features, highly calibrated probabilities).
   - Multilingual Semantic Encoder: `sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2` (~117M parameters, Apache 2.0).
     Chosen specifically because the test set introduces `France` (cross-lingual matches and accents)
     and the training set includes Hindi transliterations (India).

3. Metric Constraints:
   - Metric is Macro F_0.5 per Source 1 entity (macro-averaged over all S1 entities).
   - F_0.5 weights Precision twice as heavily as Recall (beta = 0.5):
     F_0.5 = (1.25 * Precision * Recall) / (0.25 * Precision + Recall)
   - False merges severely destroy the score, so decision thresholds are tuned strictly in [0.50, 0.99].
"""

import os
from pathlib import Path
from dataclasses import dataclass, field
from typing import Dict, Any


# -----------------------------------------------------------------------------
# Base Directories
# -----------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parent.parent

DATA_DIR = PROJECT_ROOT / "data"
FAKE_DATA_DIR = DATA_DIR / "fake_data"
REAL_DATA_DIR = PROJECT_ROOT / "student_resource" / "dataset"

OUTPUT_DIR = PROJECT_ROOT / "output"
MODEL_DIR = PROJECT_ROOT / "models"

# Ensure output and model directories exist
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
MODEL_DIR.mkdir(parents=True, exist_ok=True)
FAKE_DATA_DIR.mkdir(parents=True, exist_ok=True)


# -----------------------------------------------------------------------------
# Primary Toggle: Synthetic Bootstrap vs. Real Data
# -----------------------------------------------------------------------------
# Toggle between synthetic bootstrap testbed and real competition data.
# When True, the pipeline uses data generated by data_loading.py under data/fake_data/.
# When False, the pipeline directly reads student_resource/dataset/train and dataset/test.
USE_FAKE_DATA: bool = True


# -----------------------------------------------------------------------------
# Model & Feature Engineering Configuration
# -----------------------------------------------------------------------------
@dataclass
class ERConfig:
    """Master configuration class for the Entity Resolution Judge pipeline."""
    
    # Dataset Mode
    use_fake_data: bool = USE_FAKE_DATA
    
    # Directories
    project_root: Path = PROJECT_ROOT
    fake_data_dir: Path = FAKE_DATA_DIR
    real_data_dir: Path = REAL_DATA_DIR
    output_dir: Path = OUTPUT_DIR
    model_dir: Path = MODEL_DIR
    
    # Active Data Directories (resolved dynamically based on use_fake_data)
    @property
    def active_data_dir(self) -> Path:
        return self.fake_data_dir if self.use_fake_data else self.real_data_dir

    @property
    def train_source1_path(self) -> Path:
        return self.active_data_dir / "train" / "train_source1.tsv"

    @property
    def train_source2_path(self) -> Path:
        return self.active_data_dir / "train" / "train_source2.tsv"

    @property
    def train_source3_path(self) -> Path:
        return self.active_data_dir / "train" / "train_source3.tsv"

    @property
    def train_ground_truth_path(self) -> Path:
        return self.active_data_dir / "train" / "train_ground_truth.tsv"

    @property
    def test_source1_path(self) -> Path:
        return self.active_data_dir / "test" / "test_source1.tsv"

    @property
    def test_source2_path(self) -> Path:
        return self.active_data_dir / "test" / "test_source2.tsv"

    @property
    def test_source3_path(self) -> Path:
        return self.active_data_dir / "test" / "test_source3.tsv"

    @property
    def train_candidate_pairs_path(self) -> Path:
        return self.active_data_dir / "train" / "candidate_pairs.tsv"

    @property
    def test_candidate_pairs_path(self) -> Path:
        return self.output_dir / "candidate_pairs.tsv"

    # Submission output paths
    @property
    def output_matching_path(self) -> Path:
        return self.output_dir / "matching_results.tsv"

    @property
    def output_candidate_path(self) -> Path:
        return self.output_dir / "candidate_pairs.tsv"

    # Serialized model and metadata paths
    @property
    def model_save_path(self) -> Path:
        return self.model_dir / "lightgbm_er_judge.joblib"

    @property
    def threshold_save_path(self) -> Path:
        return self.model_dir / "optimal_threshold.json"

    @property
    def vectorizer_save_path(self) -> Path:
        return self.model_dir / "tfidf_vectorizers.joblib"

    # Multilingual Semantic Embedding Model
    # Open-source (Apache 2.0), 117M parameters, multilingual (50+ languages including EN, FR, HI).
    # Essential for cross-lingual matches (e.g. French 'Pharmacie Centrale' -> 'Central Pharmacy').
    embedding_model_name: str = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
    embedding_batch_size: int = 512 # Boosted from 64 to max out RTX 5050 VRAM (4x faster)
    use_embeddings: bool = True  # Re-enabled for maximum accuracy on GPU

    # LightGBM Classifier Parameters
    lgbm_params: Dict[str, Any] = field(default_factory=lambda: {
        "objective": "binary",
        "boosting_type": "gbdt",
        "metric": "binary_logloss",
        "n_estimators": 500, # Increased for better convergence (better F0.5)
        "learning_rate": 0.03, # Slowed down for tighter precision
        "num_leaves": 63, # Increased to capture deeper lexical patterns
        "max_depth": 7,
        "min_child_samples": 2,  # Adaptive for small bootstrap sets; scales seamlessly to millions of rows
        "subsample": 0.8,
        "colsample_bytree": 0.8,
        "random_state": 42,
        "n_jobs": -1,
        "verbose": -1,
    })

    # F_beta Metric Settings
    beta: float = 0.5  # Precision weighted 2x over Recall
    threshold_min: float = 0.50
    threshold_max: float = 0.99
    threshold_step: float = 0.01

    # Validation Split
    val_size: float = 0.20
    random_seed: int = 42


# Global configuration instance
CONFIG = ERConfig()
